CREATE TABLE [dbo].[ETIQUETATF] (
 [numlinha] [float] NOT NULL ,
 [numcarac] [float] NOT NULL ,
 [quantetiq] [float] NOT NULL ,
 [snfilial] [char] (1) NOT NULL ,
 [linfilial] [float] NOT NULL ,
 [colfilial] [float] NOT NULL ,
 [snnomefil] [char] (1) NOT NULL ,
 [linnomefil] [float] NOT NULL ,
 [colnomefil] [float] NOT NULL ,
 [sncodpatri] [char] (1) NOT NULL ,
 [lincodpat] [float] NOT NULL ,
 [colcodpatr] [float] NOT NULL ,
 [sndescr1] [char] (1) NOT NULL ,
 [lindescr1] [float] NOT NULL ,
 [coldescr1] [float] NOT NULL ,
 [sndescr2] [char] (1) NOT NULL ,
 [lindescr2] [float] NOT NULL ,
 [coldescr2] [float] NOT NULL ,
 [snnumconta] [char] (1) NOT NULL ,
 [linnumcont] [float] NOT NULL ,
 [colnumcont] [float] NOT NULL ,
 [snnomecont] [char] (1) NOT NULL ,
 [linnomecon] [float] NOT NULL ,
 [colnomecon] [float] NOT NULL ,
 [snccusto] [char] (1) NOT NULL ,
 [linccusto] [float] NOT NULL ,
 [colccusto] [float] NOT NULL ,
 [snnomecus] [char] (1) NOT NULL ,
 [linnomecus] [float] NOT NULL ,
 [colnomecus] [float] NOT NULL ,
 [snnomeprop] [char] (1) NOT NULL ,
 [linnomepro] [float] NOT NULL ,
 [colnomepro] [float] NOT NULL ,
 [snnometipo] [char] (1) NOT NULL ,
 [linnometip] [float] NOT NULL ,
 [colnometip] [float] NOT NULL ,
 [snnomeloc] [char] (1) NOT NULL ,
 [linnomeloc] [float] NOT NULL ,
 [colnomeloc] [float] NOT NULL ,
 [snfuncion] [char] (1) NOT NULL ,
 [linfuncion] [float] NOT NULL ,
 [colfuncion] [float] NOT NULL ,
 [sndataaq] [char] (1) NOT NULL ,
 [lindataaq] [float] NOT NULL ,
 [coldataaq] [float] NOT NULL ,
 [sndatainc] [char] (1) NOT NULL ,
 [lindatainc] [float] NOT NULL ,
 [coldatainc] [float] NOT NULL 
) ON [PRIMARY]
GO
