USE [master]
GO

/****** Object:  Database [WDiaferParafuso]    Script Date: 06/03/2017 10:37:05 ******/
CREATE DATABASE [WEBBI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WEBBI', FILENAME = N'D:\DBInfoWeb\WEBBI.mdf' , SIZE = 455872KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WEBBI_log', FILENAME = N'D:\DBInfoWeb\WEBBI_Log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AI
GO

ALTER DATABASE [WEBBI] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WEBBI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WEBBI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WEBBI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WEBBI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WEBBI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WEBBI] SET ARITHABORT OFF 
GO

ALTER DATABASE [WEBBI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WEBBI] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [WEBBI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WEBBI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WEBBI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WEBBI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WEBBI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WEBBI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WEBBI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WEBBI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WEBBI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WEBBI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WEBBI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WEBBI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WEBBI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WEBBI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WEBBI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WEBBI] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WEBBI] SET  MULTI_USER 
GO

ALTER DATABASE [WEBBI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WEBBI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WEBBI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WEBBI] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [WEBBI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WEBBI] SET  READ_WRITE 
GO


