


-- SQL: 1 
--------------------------------------------------------------------------------------------------------------------------------
SELECT DISTINCT	
	'SQL1'														as [Origem],
	FATOFINANCEIRO_R.OID										as [Codigo],
	FATOFINANCEIRO_R.RATOFINANCEIRO 							as [Referencia],
	FATOFINANCEIRO_R.DATA										as [Data],
	DRE.SINAL													as [Sinal],
	DRE.CODIGO + ' - ' + DRE.GRUPO								as [Tipo], 
	DRE.HIERARQUIA + ' - ' + DRE.DESCRICAO						as [Hierarquia],
	FILIAL.CODIGO												as [Filial],
	T.HIERARQUIANUMERO + ' - ' + T.NOME							as [TPO],
	FATOFINANCEIRO_R.VALOR										as [VALOR]
	--SUM(FATOFINANCEIRO_R.VALOR*FATOFINANCEIRO_R.SINAL), 
	--FATOFINANCEIRO_R.RTPO
INTO #tmp_DRE_Contrular_Email

FROM 
	FATOFINANCEIRO_R, 	CAIXABANCARIA,	TPO_R T, PESSOA_R FILIAL, AC_DRE_CONSTRULAR_R DRE
WHERE FATOFINANCEIRO_R.RFONTEPAGADORA = CAIXABANCARIA.OID
	AND DRE.HIERARQUIA = T.OBSERVACAO 
	AND T.OID =  FATOFINANCEIRO_R.RTPO
	AND FILIAL.OID = CAIXABANCARIA.RITEM
	AND FATOFINANCEIRO_R.SITUACAO = 1
	AND FATOFINANCEIRO_R.RATOFINANCEIRO <= 7
	AND FATOFINANCEIRO_R.RTPO > 7   
	AND FATOFINANCEIRO_R.RMOEDA = 113702 
	AND NOT EXISTS ( SELECT 1 FROM UTILIZACAO U WHERE U.RITEM = FATOFINANCEIRO_R.OID )  
	AND CAIXABANCARIA.RITEM IN ( 2302256, 2302250, 2653583, 2653570, 1224953, 2537974, 227135206 ) 
--GROUP BY FATOFINANCEIRO_R.RTPO

--SQL: 2 
--------------------------------------------------------------------------------------------------------------------------------
UNION ALL SELECT DISTINCT	
	'SQL2'														as [Origem],
	PG.OID														as [Codigo],
	PG.OID														as [Referencia],
	AT.DATA														as [Data],
	DRE.SINAL													as [Sinal],
	DRE.CODIGO + ' - ' + DRE.GRUPO								as [Tipo], 
	DRE.HIERARQUIA + ' - ' + DRE.DESCRICAO						as [Hierarquia],
	FILIAL.CODIGO												as [Filial],
	T.HIERARQUIANUMERO + ' - ' + T.NOME				as [TPO],
	CASE WHEN PG.VALOR < 0 THEN PG.VALOR *-1 ELSE PG.VALOR END  as [Valor]
	--SUM(PG.VALOR), 
	--CONTA.RTPO, 
	--AT.RTIPO, 
	--CAT.RSUPER
FROM  
	PAGAMENTO PG, CONTAAPAGAR_R CONTA, ACAOFINANCEIRA AF, ATOFINANCEIRO AT, CATEGORIA CAT,	
	TPO_R T, PESSOA_R FILIAL, AC_DRE_CONSTRULAR_R DRE
WHERE CONTA.RSITUACAO IN ( 2346, 2347 )
	AND DRE.HIERARQUIA = T.OBSERVACAO 
	AND T.OID = CONTA.RTPO
	AND FILIAL.OID = CONTA.RDESTINATARIO
	AND CONTA.OID = AF.RCONTA 
	AND AF.OID = PG.RACAOFINANCEIRA
	AND AF.RATOFINANCEIRO = AT.OID 
	AND AT.RTIPO IN  ( 2372, 23709, 23724 ) 
	AND NOT ( AT.RTIPO = 23724 
	AND CONTA.RTIPO = 23669 )
	AND AT.RESTORNO = 7 
	AND PG.RTIPO = CAT.OID   
	AND CONTA.RMOEDA1 = 113702 
	AND CONTA.RDESTINATARIO IN ( 2302256, 2302250, 2653583, 2653570, 1224953, 2537974, 227135206 ) 
--GROUP BY CONTA.RTPO, AT.RTIPO, CAT.RSUPER

--SQL: 3 
--------------------------------------------------------------------------------------------------------------------------------
UNION ALL SELECT DISTINCT
	'SQL3'														as [Origem],
	PG.OID														as [Codigo],
	PG.OID														as [Referencia],
	AT.DATA														as [Data],
	DRE.SINAL													as [Sinal],
	DRE.CODIGO + ' - ' + DRE.GRUPO								as [Tipo], 
	DRE.HIERARQUIA + ' - ' + DRE.DESCRICAO						as [Hierarquia],
	FILIAL.CODIGO												as [Filial],
	T.HIERARQUIANUMERO + ' - ' + T.NOME				as [TPO],
	CASE WHEN PG.VALOR < 0 THEN PG.VALOR *-1 ELSE PG.VALOR END  as [Valor]
	--SUM(PG.VALOR), 
	--CONTA.RTPO, 
	--AT.RTIPO, 
	--CAT.RSUPER
FROM  PAGAMENTO PG, CONTAARECEBER_R CONTA, ACAOFINANCEIRA AF,ATOFINANCEIRO AT, CATEGORIA CAT,
	TPO_R T, PESSOA_R FILIAL, AC_DRE_CONSTRULAR_R DRE
WHERE CONTA.RSITUACAO IN ( 2346, 2347 )
	AND DRE.HIERARQUIA = T.OBSERVACAO 
	AND T.OID = CONTA.RTPO
	AND FILIAL.OID = CONTA.RDESTINATARIO
	AND CONTA.OID = AF.RCONTA 
	AND AF.OID = PG.RACAOFINANCEIRA
	AND AF.RATOFINANCEIRO = AT.OID 
	AND AT.RTIPO IN ( 2718, 23739, 23744 )  
	AND NOT ( AT.RTIPO = 23744 AND CONTA.RTIPO = 23669 )
	AND AT.RESTORNO = 7 
	AND PG.RTIPO = CAT.OID   
	AND CONTA.RMOEDA1 = 113702 
	AND CONTA.REMITENTE IN ( 2302256, 2302250, 2653583, 2653570, 1224953, 2537974, 227135206 ) 
--GROUP BY CONTA.RTPO, AT.RTIPO, CAT.RSUPER

--SQL: 4
--------------------------------------------------------------------------------------------------------------------------------
UNION ALL SELECT DISTINCT
	'SQL4'														as [Origem],
	FATOFINANCEIRO_R.OID										as [Codigo],
	FATOFINANCEIRO_R.RATOFINANCEIRO 							as [Referencia],
	FATOFINANCEIRO_R.DATA										as [Data],
	DRE.SINAL													as [Sinal], --SELECT * FROM AC_DRE_CONSTRULAR_R
	DRE.CODIGO + ' - ' + DRE.GRUPO								as [Tipo], 
	DRE.HIERARQUIA + ' - ' + DRE.DESCRICAO						as [Hierarquia],
	FILIAL.CODIGO												as [Filial],
	T.HIERARQUIANUMERO + ' - ' + T.NOME		as [TPO],
	FATOFINANCEIRO_R.VALOR										as [VALOR]
	--SUM(FATOFINANCEIRO_R.VALOR*FATOFINANCEIRO_R.SINAL), 
	--FATOFINANCEIRO_R.RTPO
FROM FATOFINANCEIRO_R, UTILIZACAO U, TPO_R T, PESSOA_R FILIAL, AC_DRE_CONSTRULAR_R DRE
WHERE FATOFINANCEIRO_R.OID = U.RITEM
	AND DRE.HIERARQUIA = T.OBSERVACAO 
	AND T.OID =  FATOFINANCEIRO_R.RTPO
	AND FILIAL.OID = U.RUTILIZADO
	AND FATOFINANCEIRO_R.SITUACAO = 1
	AND FATOFINANCEIRO_R.RATOFINANCEIRO <= 7
	AND FATOFINANCEIRO_R.RTPO > 7   
	AND FATOFINANCEIRO_R.RMOEDA = 113702 
	AND U.RUTILIZADO IN ( 2302256, 2302250, 2653583, 2653570, 1224953, 2537974, 227135206 ) 
--GROUP BY FATOFINANCEIRO_R.RTPO


--SQL: 5
--------------------------------------------------------------------------------------------------------------------------------
UNION ALL SELECT DISTINCT
	'SQL5'														as [Origem],
	FATOFINANCEIRO_R.OID										as [Codigo],
	FATOFINANCEIRO_R.RATOFINANCEIRO 							as [Referencia],
	FATOFINANCEIRO_R.DATA										as [Data],
	DRE.SINAL													as [Sinal], --SELECT * FROM AC_DRE_CONSTRULAR_R
	DRE.CODIGO + ' - ' + DRE.GRUPO								as [Tipo], 
	DRE.HIERARQUIA + ' - ' + DRE.DESCRICAO						as [Hierarquia],
	FILIAL.CODIGO												as [Filial],
	T.HIERARQUIANUMERO + ' - ' + T.NOME		as [TPO],
	FATOFINANCEIRO_R.VALOR										as [VALOR]
	--SUM(FATOFINANCEIRO_R.VALOR*FATOFINANCEIRO_R.SINAL), 
	--FATOFINANCEIRO_R.RTPO
FROM 
	FATOFINANCEIRO_R, CAIXABANCARIA, ATOFINANCEIRO ATO, TPO_R T, PESSOA_R FILIAL, AC_DRE_CONSTRULAR_R DRE
WHERE FATOFINANCEIRO_R.RFONTEPAGADORA = CAIXABANCARIA.OID
	AND DRE.HIERARQUIA = T.OBSERVACAO 
	AND T.OID =  FATOFINANCEIRO_R.RTPO
	AND FILIAL.OID = CAIXABANCARIA.RITEM
	AND FATOFINANCEIRO_R.SITUACAO = 1
	AND FATOFINANCEIRO_R.RATOFINANCEIRO > 7
	AND FATOFINANCEIRO_R.RATOFINANCEIRO = ATO.OID 
	AND ATO.RTIPO IN ( 29852, 23724, 23744, 38032 ) 
	AND FATOFINANCEIRO_R.RTPO > 7   
	AND FATOFINANCEIRO_R.RMOEDA = 113702 
	AND CAIXABANCARIA.RITEM IN ( 2302256, 2302250, 2653583, 2653570, 1224953, 2537974, 227135206 ) 
--GROUP BY FATOFINANCEIRO_R.RTPO


-- SQL: 6
--------------------------------------------------------------------------------------------------------------------------------
UNION ALL SELECT DISTINCT
	'SQL6'														as [Origem],
	DO.OID														as [Codigo],
	DO.OID														as [Referencia],
	DO.EMISSAO													as [Data],
	DRE.SINAL													as [Sinal], --SELECT * FROM AC_DRE_CONSTRULAR_R
	DRE.CODIGO + ' - ' + DRE.GRUPO								as [Tipo], 
	DRE.HIERARQUIA + ' - ' + DRE.DESCRICAO						as [Hierarquia],
	F.FILIAL													as [Filial],
	T.HIERARQUIANUMERO + ' - ' + T.NOME									as [TPO],
	DO.VALORNAMOEDA1											as [VALOR]
	--SUM(DO.VALORNAMOEDA1) AS Valor, 
	--T.OID, 
	--1 
FROM 
	DOCDEORIGEM_R DO, NFSAIDACAD NFS, NFENTRACAD NFE, FILIALCAD F,
	TPO_R T, AC_DRE_CONSTRULAR_R DRE
WHERE DO.OID = NFS.OIDDOCDEORIGEM 
	AND DRE.HIERARQUIA = T.OBSERVACAO 
	AND DO.OID = NFE.OIDDOCDEORIGEM 
	AND NFS.TPO = T.HIERARQUIANUMERO 
	AND NFS.FILIAL = F.FILIAL 
	AND T.HIERARQUIAMASCARA LIKE '9%'  
	AND DO.RMOEDA1 = 113702 
	AND F.OID IN ( 2302256, 2302250, 2653583, 2653570, 1224953, 2537974, 227135206 )

UNION ALL SELECT DISTINCT
	'SQL7'														as [Origem],
	DO.OID														as [Codigo],
	DO.OID														as [Referencia],
	DO.EMISSAO													as [Data],
	DRE.SINAL													as [Sinal], --SELECT * FROM AC_DRE_CONSTRULAR_R
	DRE.CODIGO + ' - ' + DRE.GRUPO								as [Tipo], 
	DRE.HIERARQUIA + ' - ' + DRE.DESCRICAO						as [Hierarquia],
	F.FILIAL													as [Filial],
	T.HIERARQUIANUMERO + ' - ' + T.NOME									as [TPO],
	DO.VALORNAMOEDA1											as [VALOR]
	--SUM(DO.VALORNAMOEDA1) AS Valor, 
	--T.OID, 
	--1 
FROM DOCDEORIGEM_R DO, NFSAIDACAD NFS, NFENTRACAD NFE, FILIALCAD F,
	TPO_R T, AC_DRE_CONSTRULAR_R DRE
WHERE DO.OID = NFS.OIDDOCDEORIGEM 
	AND DRE.HIERARQUIA = T.OBSERVACAO 
	AND DO.OID = NFE.OIDDOCDEORIGEM 
	AND NFE.TPO = T.HIERARQUIANUMERO 
	AND NFE.FILIAL = F.FILIAL 
	AND T.HIERARQUIAMASCARA LIKE '9%'  
	AND DO.RMOEDA1 = 113702 
	AND F.OID IN ( 2302256, 2302250, 2653583, 2653570, 1224953, 2537974, 227135206 ) 
	AND NFE.TPO != NFS.TPO 



-- Listar DRE
------------------------------------------------------------------------------------
select 
	--FILIAL, 
	TIPO,
	SINAL,
	Hierarquia,
	TPO,
	SUM(VALOR)
	 
from #tmp_DRE_Contrular_Email 
where 
	--filial = '01' and 
	data between '20180201' and '20180228'
group by 
		--FILIAL, 
		TIPO, SINAL, Hierarquia 
		,TPO
order by 
	--filial, 
	TIPO,Hierarquia