-- 11 - Despesas Financeiras
--------------------------------------------------------------------------------
SELECT 
	FATOFINANCEIRO_R.OID as [Codigo],
	FATOFINANCEIRO_R.DATA as [Data],
	'-' as [Sinal],
	'11 - Despesas Financeiras' as [Tipo], 
	'Financeiras' as [Operacao],
	CASE 
		WHEN FATOFINANCEIRO_R.RTPO = 7985517 THEN '11.01 - ' + TPO_R.NOME
		WHEN FATOFINANCEIRO_R.RTPO = 2300513 THEN '11.03 - ' + TPO_R.NOME
		WHEN FATOFINANCEIRO_R.RTPO = 2300516 THEN '11.05 - ' + TPO_R.NOME
		
	ELSE 'Nivel 11 Indeterminado - ' + TPO_R.NOME
	end as [Hierarquia],
	FILIAL.CODIGO as [Filial],
	FATOFINANCEIRO_R.VALOR*FATOFINANCEIRO_R.SINAL as [Valor]

FROM 
	FATOFINANCEIRO_R, CAIXABANCARIA, TPO_R, PESSOA_R FILIAL
WHERE 
	FILIAL.OID = CAIXABANCARIA.RITEM
	AND FATOFINANCEIRO_R.RFONTEPAGADORA = CAIXABANCARIA.OID
	AND TPO_R.OID =  FATOFINANCEIRO_R.RTPO
	AND FATOFINANCEIRO_R.SITUACAO = 1
	AND FATOFINANCEIRO_R.RATOFINANCEIRO <= 7
	AND FATOFINANCEIRO_R.RTPO > 7   
	AND FATOFINANCEIRO_R.RMOEDA = 113702 
	AND NOT EXISTS ( SELECT 1 FROM UTILIZACAO U WHERE U.RITEM = FATOFINANCEIRO_R.OID )  
	AND CAIXABANCARIA.RITEM IN ( 2302256, 2302250, 2653583, 2653570, 1224953, 2537974, 227135206 ) 
	and FATOFINANCEIRO_R.RTPO in (
			7985517, -- Tarifas Bancárias
			2300513, -- Juros Bancários
			2300516 --IOF
	)
