----------------------------------------------------------------------------------------------------------------------------------------------------
-- Script para extrair a tabela BASECALFAT (Redução de Base)
----------------------------------------------------------------------------------------------------------------------------------------------------
select 'insert into basecalfat (
codpro,
basecont,
basencont,
codmens,
aliqcont,
aliqncont,
percsubtri,
estadoorigem,
estadodestino,
basecalcproduto,
aliquotaproduto,
tpo,
cfo,
Classificacaocliente,
TipoCliente,
percbasedespesas,
TIPOSUBSTVENDA,
CFONCONT,
CODMENSNCONT,
CF,
ALQDebICMSST,
ALQCREDICMSST,
BaseCredICMSST,
BaseDebICMSST,
ManterBasePadraoReducao)
values ('''+codpro+''',',
basecont,',',
basencont,','''+ltrim(rtrim(codmens))+''',',
aliqcont,',',
aliqncont,',',
percsubtri,',',
''''+ltrim(rtrim(estadoorigem))+''',',
''''+ltrim(rtrim(estadodestino))+''',',
''''+ltrim(rtrim(basecalcproduto))+''',',
''''+ltrim(rtrim(aliquotaproduto))+''',',
''''+rtrim(ltrim((tpo)))+''',',
''''+rtrim(ltrim((cfo)))+''',',
''''+rtrim(ltrim((tipocliente)))+''',',
isnull(percbasedespesas,0),',',
''''+TIPOSUBSTVENDA+''',',
''''+rtrim(ltrim((isnull(CFONCONT,''))))+''',',
''''+rtrim(ltrim((isnull(CODMENSNCONT,''))))+''',',
''''+rtrim(ltrim((CF)))+''',',
isnull(ALQDebICMSST,0),',',
isnull(ALQCREDICMSST,0),',',
isnull(BaseCredICMSST,0)',',
isnull(BaseDebICMSST,0)',',
','''+rtrim(ltrim((ManterBasePadraoReducao)))+''')'
 
 from basecalfat

