DROP TABLE #tmp_DRE_Deducoes_de_Vendas

SELECT 
	DISTINCT 
	PAGTO.OID,
	ATO.DATA,
	'2 - Deduções de Vendas' as [Tipo], 
	'Descontos' as [Operacao],
	'2.1 - Descontos Concedidos' [Hierarquia],
	'01' AS fILIAL,
	PAGTO.VALOR into #tmp_DRE_Deducoes_de_Vendas

FROM ATOFINANCEIRO_R ATO 
 JOIN ACAOFINANCEIRA ACAO ON ATO.OID = ACAO.RATOFINANCEIRO 
 JOIN PAGAMENTO PAGTO ON ACAO.OID = PAGTO.RACAOFINANCEIRA 
 JOIN CONTAARECEBER_R CONTA ON ACAO.RCONTA = CONTA.OID 
 JOIN PESSOA_R CLIENTE ON CONTA.RDESTINATARIO = CLIENTE.OID 
 JOIN PESSOA_R FILIAL ON CONTA.REMITENTE = FILIAL.OID 
 JOIN CATEGORIA ON PAGTO.RTIPO = CATEGORIA.OID 
 JOIN ITEM DO ON CONTA.RDOCDEORIGEM = DO.OID 
 LEFT JOIN FATOFINANCEIRO_R FATO ON ATO.OID = FATO.RATOFINANCEIRO 
 LEFT JOIN ADITIVO ON CONTA.OID = ADITIVO.RITEM
WHERE 
	CONTA.OID > 7 
	--And CLIENTE.NOME like '%Alcides stock%'
	AND CATEGORIA.RSUPER = 2337
	AND ATO.RTIPO IN ( 2718 ) 
	AND ATO.RESTORNO = 7 
	--and PAGTO.rtipo <> 2159778
	--AND CONTA.REMITENTE = 2302250 
	AND PAGTO.RMOEDA = 113702  
	--AND ATO.DATA >= CONVERT(DATETIME,'01/02/2018',103) 
	--AND ATO.DATA <= CONVERT(DATETIME,'28/02/2018',103)
UNION ALL
SELECT 
	DISTINCT 
	PAGTO.OID,
	ATO.DATA,
	'2 - Deduções de Vendas' as [Tipo], 
	'Descontos' as [Operacao],
	'2.1 - Descontos Concedidos' [Hierarquia],
	'01' AS fILIAL,
	PAGTO.VALOR
FROM ATOFINANCEIRO_R ATO 
 JOIN ACAOFINANCEIRA ACAO ON ATO.OID = ACAO.RATOFINANCEIRO 
 JOIN PAGAMENTO PAGTO ON ACAO.OID = PAGTO.RACAOFINANCEIRA 
 JOIN CONTAARECEBER_R CONTA ON ACAO.RCONTA = CONTA.OID 
 JOIN PESSOA_R CLIENTE ON CONTA.RDESTINATARIO = CLIENTE.OID 
 JOIN PESSOA_R FILIAL ON CONTA.REMITENTE = FILIAL.OID 
 JOIN CATEGORIA ON PAGTO.RTIPO = CATEGORIA.OID 
 JOIN ITEM DO ON CONTA.RDOCDEORIGEM = DO.OID 
 JOIN AGRUPAMENTO AG ON ATO.OID = AG.RGRUPO AND AG.RPAPEL = 33978 
 JOIN FATOFINANCEIRO_R FATO ON AG.RITEM = FATO.RATOFINANCEIRO 
 LEFT JOIN ADITIVO ON CONTA.OID = ADITIVO.RITEM
WHERE CONTA.OID > 7 
	--and CLIENTE.NOME like '%Gilberto%'
	AND CATEGORIA.RSUPER = 2337
	AND ATO.RTIPO = 23744 
	--and PAGTO.rtipo <> 2159778
	AND ATO.RESTORNO = 7 
	--AND CONTA.REMITENTE = 2302250 
	AND PAGTO.RMOEDA = 113702  
	--AND ATO.DATA >= CONVERT(DATETIME,'01/02/2018',103) 
	--AND ATO.DATA <= CONVERT(DATETIME,'28/02/2018',103)
	AND CONTA.RTIPO != 23669 

-- Encargos:
-----------------------------------------------------------------------------------------------------
UNION ALL SELECT 
	DISTINCT
	PAGTO.OID,
	ATO.DATA,
	'12 - Receitas Financeiras' as [Tipo], 
	'Encargos' as [Operacao],
	'12.1 - Encargos' [Hierarquia],
	'01' AS fILIAL,
	PAGTO.VALOR 
FROM ATOFINANCEIRO_R ATO 
 JOIN ACAOFINANCEIRA ACAO ON ATO.OID = ACAO.RATOFINANCEIRO 
 JOIN PAGAMENTO PAGTO ON ACAO.OID = PAGTO.RACAOFINANCEIRA 
 JOIN CONTAARECEBER_R CONTA ON ACAO.RCONTA = CONTA.OID 
 JOIN PESSOA_R CLIENTE ON CONTA.RDESTINATARIO = CLIENTE.OID 
 JOIN PESSOA_R FILIAL ON CONTA.REMITENTE = FILIAL.OID 
 JOIN CATEGORIA ON PAGTO.RTIPO = CATEGORIA.OID 
 JOIN ITEM DO ON CONTA.RDOCDEORIGEM = DO.OID 
 LEFT JOIN FATOFINANCEIRO_R FATO ON ATO.OID = FATO.RATOFINANCEIRO 
 LEFT JOIN ADITIVO ON CONTA.OID = ADITIVO.RITEM
WHERE 
	CONTA.OID > 7 
	--And CLIENTE.NOME like '%Alcides stock%'
	AND CATEGORIA.RSUPER = 2330
	AND ATO.RTIPO IN ( 2718 ) 
	AND ATO.RESTORNO = 7 
	--and PAGTO.rtipo <> 2159778
	--AND CONTA.REMITENTE = 2302250 
	AND PAGTO.RMOEDA = 113702  
	--AND ATO.DATA >= CONVERT(DATETIME,'01/02/2018',103) 
	--AND ATO.DATA <= CONVERT(DATETIME,'28/02/2018',103)

UNION ALL SELECT 
	DISTINCT
	PAGTO.OID,
	ATO.DATA,
	'12 - Receitas Financeiras' as [Tipo], 
	'Encargos' as [Operacao],
	'12.1 - Encargos' [Hierarquia],
	'01' AS fILIAL,
	PAGTO.VALOR 
FROM ATOFINANCEIRO_R ATO 
 JOIN ACAOFINANCEIRA ACAO ON ATO.OID = ACAO.RATOFINANCEIRO 
 JOIN PAGAMENTO PAGTO ON ACAO.OID = PAGTO.RACAOFINANCEIRA 
 JOIN CONTAARECEBER_R CONTA ON ACAO.RCONTA = CONTA.OID 
 JOIN PESSOA_R CLIENTE ON CONTA.RDESTINATARIO = CLIENTE.OID 
 JOIN PESSOA_R FILIAL ON CONTA.REMITENTE = FILIAL.OID 
 JOIN CATEGORIA ON PAGTO.RTIPO = CATEGORIA.OID 
 JOIN ITEM DO ON CONTA.RDOCDEORIGEM = DO.OID 
 JOIN AGRUPAMENTO AG ON ATO.OID = AG.RGRUPO AND AG.RPAPEL = 33978 
 JOIN FATOFINANCEIRO_R FATO ON AG.RITEM = FATO.RATOFINANCEIRO 
 LEFT JOIN ADITIVO ON CONTA.OID = ADITIVO.RITEM
WHERE CONTA.OID > 7 
	--and CLIENTE.NOME like '%Alcides stock%'
	AND CATEGORIA.RSUPER = 2330
	AND ATO.RTIPO = 23744 
	--and PAGTO.rtipo <> 2159778
	AND ATO.RESTORNO = 7 
	--AND CONTA.REMITENTE = 2302250 
	AND PAGTO.RMOEDA = 113702  
	--AND ATO.DATA >= CONVERT(DATETIME,'01/02/2018',103) 
	--AND ATO.DATA <= CONVERT(DATETIME,'28/02/2018',103)
	AND CONTA.RTIPO != 23669 


	-- Listar DRE
------------------------------------------------------
select 	Tipo, Hierarquia, filial, sum(valor) as Valor
from #tmp_DRE_Deducoes_de_Vendas
where DATA >= CONVERT(DATETIME,'01/01/2018',103) and DATA <= CONVERT(DATETIME,'14/03/2018',103)
group by 	Tipo, Hierarquia, filial
