-- muda categoria da opção para tipo CADASTRO, para permitir acessos correspondentes (só não exlui, somente leitura, etc.)

--ENTRADAS - COMPRAS - SEM EMISSÃO
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35309
GO
--ENTRADAS - COMPRAS - COM EMISSÃO
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35310
GO
--ENTRADAS - DEVOLUÇÃO DE VENDA - SEM EMISSÃO
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35311
GO
--ENTRADAS - DEVOLUÇÃO DE VENDA - COM EMISSÃO
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35312
GO
--ENTRADAS - OUTRAS ENTRADAS - SEM EMISSÃO - RETORNO
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35315
GO
--ENTRADAS - OUTRAS ENTRADAS - SEM EMISSÃO - ENTRADA
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35316
GO
--ENTRADAS - OUTRAS ENTRADAS - COM EMISSÃO - RETORNO
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35317
GO
--ENTRADAS - OUTRAS ENTRADAS - COM EMISSÃO - ENTRADA
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35318
GO
--ENTRADAS - ENTRADA SIMPLIFICADA
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35307
GO
--SAIDAS - VENDAS
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35322
GO
--SAIDAS - TRANSFERENCIAS
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35323
GO
--SAIDAS - DEVOLUÇÕES DE COMPRAS
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35324
GO
--SAIDAS - OUTRAS SAIDAS - COM RETORNO
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35334
GO
--SAIDAS - OUTRAS SAIDAS - SEM RETORNO - TRIBUTADAS
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35334
GO
--SAIDAS - OUTRAS SAIDAS - SEM RETORNO - NÃO TRIBUTADAS
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35335
GO
--SAÍDAS - COMPLEMENTAÇÃO - VENDAS
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35336
GO
--SAÍDAS - COMPLEMENTAÇÃO - OUTRAS SAÍDAS - COM RETORNO
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35338
GO
--SAÍDAS - COMPLEMENTAÇÃO - OUTRAS SAÍDAS - SEM RETORNO - TRIBUTADAS
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35340
GO
--SAÍDAS - COMPLEMENTAÇÃO - OUTRAS SAÍDAS - SEM RETORNO - NÃO TRIBUTADAS
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35341
GO
--SAIDAS - SAIDA SIMPLIFICADA
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35328
GO
--SAIDAS - VENDA DE SERVIÇOS
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35331
GO
--SAÍDAS - EMISSAO NF CONSUMIDOR
update LISTADEOBJETOS set RCATEGORIA=1085 where OID=35329
go

